name: glass_button_package
description: This project includes a sample button for educational purposes that demonstrates the glass effect.
version: 0.0.1
homepage: https://github.com/Allahverdyy/glass_button_package
documentation: https://github.com/Allahverdyy/glass_button_package/blob/main/README.md

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
